<a href="https://colab.research.google.com/github/Divya-Dhananjayan/IPSR-internship/blob/main/Task2Internship_DataMerging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Step 2: Data Merging
=====================

First we are trying to merge the first 2 data frames df1 and df2.Then the resultant is merged with the third data frame df3 . Thus we merge whole data into a single one

For merging we are not considering the whole columns of each data sets.
We are picking some of the required columns only

In [ ]:

# From df1 we are excluding state and city columns as these columns are not cleaned


df1 = df1[[
    'ranking_year','ranking_category',
    'institute_id','institute_name',
    'category','no. of phd students'
    ]]

In [ ]:

# From df2 we are excluding state and city columns as these columns are not cleaned

df2 = df2[[
    'ranking_year','ranking_category',
    'institute_id','institute_name',
    'score','rank'
     ]]

In [ ]:
# 'Overa all score' column is renamed to score as it is same as the score column of df3


df3_splitted.rename(columns= {'Overall Score': 'score'} ,inplace = True)

In [ ]:
# From df3_splitted we are excluding state and city columns as these columns
# are not cleaned
# The resultant is saved to df3 for convenience

df3 = df3_splitted[
    ['ranking_year','ranking_category','institute_id','institute_name',
     'Graduation Outcomes','Outreach and Inclusivity','score','Perception','Qualitative Research'
     ,'Quantitative Research','Research and Professional Practice','Students and Faculty Contribution',
     'Teaching, Learning and Resources']
    ]

In [ ]:
df3

score_category,ranking_year,ranking_category,institute_id,institute_name,Graduation Outcomes,Outreach and Inclusivity,score,Perception,Qualitative Research,Quantitative Research,Research and Professional Practice,Students and Faculty Contribution,"Teaching, Learning and Resources"
0,2016,Engineering,NIRF-ENGG-1-2449860060,C.V.Raman College Of Engineering-Bhubaneswar,81.69,55.36,53.91,23.00,NaN,NaN,56.85,NaN,46.77
1,2016,Engineering,NIRF-ENGG-1-2449883879,Bengal Institute Of Technology,92.06,47.01,50.33,59.00,NaN,NaN,50.00,NaN,28.70
2,2016,Engineering,NIRF-ENGG-1-2449912182,Bannari Amman Institute Of Technology-Sathyama...,77.22,62.78,56.21,27.00,NaN,NaN,58.11,NaN,51.61
3,2016,Engineering,NIRF-ENGG-1-2449920071,"Amrita Viswa Vidyapeetham-Amrita Nagar (Po) ,E...",81.38,65.70,58.78,36.00,NaN,NaN,53.42,NaN,57.04
4,2016,Engineering,NIRF-ENGG-1-2449931180,Coimbatore Institute Of Technology-Coimbatore,82.91,68.54,62.58,74.00,NaN,NaN,62.54,NaN,48.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6308,2024,University,IR-O-U-0575,jadavpur university,89.92,49.94,65.39,63.74,NaN,NaN,51.35,NaN,68.83
6309,2024,University,IR-O-U-0642,shiv nadar university,59.74,66.79,49.80,20.86,NaN,NaN,25.51,NaN,71.43
6310,2024,University,IR-O-U-0739,madan mohan malaviya university of technology,63.84,70.12,46.33,19.63,NaN,NaN,15.78,NaN,66.18
6311,2024,University,IR-O-U-0747,chandigarh university,78.18,77.52,59.96,41.19,NaN,NaN,39.66,NaN,68.50
6312,2024,University,IR-O-U-0749,manipal university jaipur,63.73,66.15,49.50,27.16,NaN,NaN,30.02,NaN,61.36

In [ ]:
# Merging df1 and df2


df_merged_df1df2 = pd.merge(left = df1 , right = df2 ,
                            on = ['ranking_year','ranking_category',
                                  'institute_id','institute_name']
                                  ,how = 'outer')

In [ ]:
df_merged_df1df2.isnull().sum()

ranking_year              0
ranking_category          0
institute_id              0
institute_name            0
category               1963
no. of phd students    1963
score                    30
rank                      0
dtype: int64

In [ ]:

# The resultant is trying to merge with df3

df_merged_df1df2df3 = pd.merge(left =df_merged_df1df2 , right = df3 ,
                               on=['ranking_year','ranking_category',
                                   'institute_id','institute_name','score']
                               ,how = 'outer')

In [ ]:
df_merged_df1df2df3

,ranking_year,ranking_category,institute_id,institute_name,category,no. of phd students,score,rank,Graduation Outcomes,Outreach and Inclusivity,Perception,Qualitative Research,Quantitative Research,Research and Professional Practice,Students and Faculty Contribution,"Teaching, Learning and Resources"
0,2016,Engineering,NIRF-ENGG-1-2449860060,C.V.Raman College Of Engineering-Bhubaneswar,NaN,NaN,53.91,74,81.69,55.36,23.00,NaN,NaN,56.85,NaN,46.77
1,2016,Engineering,NIRF-ENGG-1-2449883879,Bengal Institute Of Technology,NaN,NaN,50.33,91,92.06,47.01,59.00,NaN,NaN,50.00,NaN,28.70
2,2016,Engineering,NIRF-ENGG-1-2449912182,Bannari Amman Institute Of Technology-Sathyama...,NaN,NaN,56.21,62,77.22,62.78,27.00,NaN,NaN,58.11,NaN,51.61
3,2016,Engineering,NIRF-ENGG-1-2449920071,"Amrita Viswa Vidyapeetham-Amrita Nagar (Po) ,E...",NaN,NaN,58.78,50,81.38,65.70,36.00,NaN,NaN,53.42,NaN,57.04
4,2016,Engineering,NIRF-ENGG-1-2449931180,Coimbatore Institute Of Technology-Coimbatore,NaN,NaN,62.58,34,82.91,68.54,74.00,NaN,NaN,62.54,NaN,48.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11301,2024,University,IR-O-U-0739,madan mohan malaviya university of technology,Part Time,0.0,46.33,94,63.84,70.12,19.63,NaN,NaN,15.78,NaN,66.18
11302,2024,University,IR-O-U-0747,chandigarh university,Full Time,1006.0,59.96,20,78.18,77.52,41.19,NaN,NaN,39.66,NaN,68.50
11303,2024,University,IR-O-U-0747,chandigarh university,Part Time,601.0,59.96,20,78.18,77.52,41.19,NaN,NaN,39.66,NaN,68.50
11304,2024,University,IR-O-U-0749,manipal university jaipur,Full Time,281.0,49.50,64,63.73,66.15,27.16,NaN,NaN,30.02,NaN,61.36
11305,2024,University,IR-O-U-0749,manipal university jaipur,Part Time,349.0,49.50,64,63.73,66.15,27.16,NaN,NaN,30.02,NaN,61.36

In [ ]:
df_merged_df1df2df3.isnull().sum()

ranking_year                              0
ranking_category                          0
institute_id                              0
institute_name                            0
category                               1964
no. of phd students                    1964
score                                    30
rank                                      1
Graduation Outcomes                     230
Outreach and Inclusivity                 30
Perception                               30
Qualitative Research                  11106
Quantitative Research                 11106
Research and Professional Practice      230
Students and Faculty Contribution     11106
Teaching, Learning and Resources        230
dtype: int64

In [ ]:
# Formating the institute name column properly with first letter of each word capital

df_merged_df1df2df3['institute_name']=df_merged_df1df2df3['institute_name'].str.title()


df_merged_df1df2df3.drop_duplicates()

,ranking_year,ranking_category,institute_id,institute_name,category,no. of phd students,score,rank,Graduation Outcomes,Outreach and Inclusivity,Perception,Qualitative Research,Quantitative Research,Research and Professional Practice,Students and Faculty Contribution,"Teaching, Learning and Resources"
0,2016,Engineering,NIRF-ENGG-1-2449860060,C.V.Raman College Of Engineering-Bhubaneswar,NaN,NaN,53.91,74,81.69,55.36,23.00,NaN,NaN,56.85,NaN,46.77
1,2016,Engineering,NIRF-ENGG-1-2449883879,Bengal Institute Of Technology,NaN,NaN,50.33,91,92.06,47.01,59.00,NaN,NaN,50.00,NaN,28.70
2,2016,Engineering,NIRF-ENGG-1-2449912182,Bannari Amman Institute Of Technology-Sathyama...,NaN,NaN,56.21,62,77.22,62.78,27.00,NaN,NaN,58.11,NaN,51.61
3,2016,Engineering,NIRF-ENGG-1-2449920071,"Amrita Viswa Vidyapeetham-Amrita Nagar (Po) ,E...",NaN,NaN,58.78,50,81.38,65.70,36.00,NaN,NaN,53.42,NaN,57.04
4,2016,Engineering,NIRF-ENGG-1-2449931180,Coimbatore Institute Of Technology-Coimbatore,NaN,NaN,62.58,34,82.91,68.54,74.00,NaN,NaN,62.54,NaN,48.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11301,2024,University,IR-O-U-0739,Madan Mohan Malaviya University Of Technology,Part Time,0.0,46.33,94,63.84,70.12,19.63,NaN,NaN,15.78,NaN,66.18
11302,2024,University,IR-O-U-0747,Chandigarh University,Full Time,1006.0,59.96,20,78.18,77.52,41.19,NaN,NaN,39.66,NaN,68.50
11303,2024,University,IR-O-U-0747,Chandigarh University,Part Time,601.0,59.96,20,78.18,77.52,41.19,NaN,NaN,39.66,NaN,68.50
11304,2024,University,IR-O-U-0749,Manipal University Jaipur,Full Time,281.0,49.50,64,63.73,66.15,27.16,NaN,NaN,30.02,NaN,61.36
11305,2024,University,IR-O-U-0749,Manipal University Jaipur,Part Time,349.0,49.50,64,63.73,66.15,27.16,NaN,NaN,30.02,NaN,61.36

In [ ]:
m = df_merged_df1df2df3.drop_duplicates()

In [ ]:
# Saving merged datasheets

m.to_csv('3dfs_merged.csv')